### ISSUE TITLE
tab completion for /help with essentialsx

### ISSUE THREAD

**Issue by Tavies** [YouHaveTrouble/CommandWhitelist#14]
Hello, I'm using a 1.16.5 paper server with the essentialsx plugin and was hoping to hide the /help tab completion items. When typing /help then space it shows a list of every command. I verified that the user is not OP and only has the commandwhitelist.commands.default permission as well as the command associated essentials permissions like essentials.help
Everything else seems to be working great!

Ideally /help should only show the same list as /[tab] (or nothing as the help file would also be able to list the commands).
I tested the whitelist without essentialsx and I could manually add every single command to the list, however once I reinstalled the plugin, they were no longer blocked by the whitelist.

1. Server 1.16.5 paper, Installed plugins CommandWhitelist 1.7.0, luckperms, vault, worldedit, worldguard, essentialsX
2. Type /help and press space, see an excessive list of commands. 

![whitelist help](https://user-images.githubusercontent.com/78396492/106564430-0d181280-64e2-11eb-84bd-6c39328ea77d.png)

If there is a way in the whitelist to simply block all subcommands from /help that would also help a lot.
Thank you for your time!

**Comment by YouHaveTrouble** [comment]
It took me a while, but I figured out what was causing this. Essentials is adding the tab completions multiple times instead of just once. I've implemented workaround for this in [latest version](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.7.1). I also brought the issue up in essentials discord, so you don't have to do that ^^

**Comment by Tavies** [comment]
Thank you again!
