### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jokbon** [YouHaveTrouble/CommandWhitelist#16]
**Suggestion iam not programer, but could u achieve something liek this?**
```
#Enabled servers
auth=[
    "example_permision",
    "example_permision_2"
     ]
hub=[
    "example_permision",
    "example_permision_2"
     ]

#
#Settings for permisions
permisions {
    example_permision=[
            mode=whitelist
            whitelist=[
                "login"
                "register"
            ]
            blacklist=[
                "say"
            ]
 }
```

**Comment by YouHaveTrouble** [comment]
Technically yes, but also technically, it's more efficient to block bukkit commands on bukkit level. Also less complicated on the config.  If you find anyone who wants to PR changes you want, sure, but I'm most likely not going to add that myself.

**Comment by jokbon** [comment]
Its actualy easy configuration. it looks complicated but its not.
You specify servers, and permisions on those servers.

The rest is permision list with blocked commands.

**Comment by YouHaveTrouble** [comment]
The issue here is efficiency. There is a difference between handling commands proxy-side and server-side. The more commands you add to the lists, more plugin has to iterate through, if it's done on spigot server, most it will do is stall a tick for a millisecond or two, doing any operation on proxy level while you could handle it on spigot side it's just not a good idea, way more things could go wrong. That's also why the option to enable protocollib command filtering is described as "only enable when you need it", as it also uses network threads to do its stuff.

**Comment by jokbon** [comment]
Any idea how to let bungee comands when player is specific servers then?

**Comment by YouHaveTrouble** [comment]
if you have luckperms and you use database to sync the permissions. You can just create group per server and grant that permission in server context ^^
