### ISSUE TITLE
Be able to turn off the command blocker

### ISSUE THREAD

**Issue by xFreakss** [YouHaveTrouble/CommandWhitelist#54]
**Is your feature request related to a problem? Please describe.**
My problem is that i need some way to manage tab completions without having to deal with the command blocker feature, there's no reason for me to use it if i got an permissions plugin 

**Describe the solution you'd like**
A command or switch in the config to be able to use the plugin only for tab completion management 

**Describe alternatives you've considered**
none

**Additional context**

**Comment by YouHaveTrouble** [comment]
The general rule on this is - if you need to get rid of tab completion without getting rid of the ability to execute the command, you're doing something wrong. If you're trying to set the command to npc or gui, try making them execute console command instead of making player execute any. If you believe otherwise, consider alternatives :)
