### ISSUE TITLE
Why plugin 

### ISSUE THREAD

**Issue by TymekSL** [YouHaveTrouble/CommandWhitelist#77]
Why plugin doesnt support 1.8+ ?

**Comment by 4drian3d** [comment]
Why should it support such old versions?

**Comment by YouHaveTrouble** [comment]
Less than 10% of total servers use 1.12 or lower and command system is entirely different, forcing basically entirely different logic for older versions. This basically would make as much work as 2 separate plugins to maintain.
Also, version 1.x supported 1.8+ and 95% of bugs were due to shit behavior of old command system.
